version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    container_name: "laravelappProBO"
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html